compile:
		gcc -o checkstatus Exit_Status_hw04.c -lm
		gcc -o copyfile copyfile.c

runcheckstatus:
		./checkstatus

runcopyfile1:
		./copyfile test.txt outputfile.txt 1 

runcopyfile3:
		./copyfile test.txt output2.txt 3

runcopyfile5:
		./copyfile test.txt output3.txt 5

runcopyfile7:
		./copyfile test.txt output4.txt 7

runcopyfile9:
		./copyfile test.txt output5.txt 9

runcopyfile11:
		./copyfile test.txt output6.txt 11

runcopyfile13:
		./copyfile test.txt output7.txt 13